name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    #timeout-minutes: 60
    runs-on: ubuntu-latest
    # Ajoute "permissions" pour s'assurer que le bot GitHub Actions dispose des droits de modification (write) sur le contenu du dépôt, ce qui est nécessaire pour pousser sur gh-pages.
    permissions:      
       contents: write  # Donne l'accès en écriture pour le contenu du dépôt sur gth-page
     
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests with allure report 
      run: npm run  test:allure
    - name: Upload Allure results # Sauvegarde du rapport Allure depuis le projet vers le CI
      uses: actions/upload-artifact@v4 #chargement du rapport dans un artifact
      with:
        name: allure-report
        path: allure-report  # Le répertoire contenant le rapport généré par Allure

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Utilise le token GitHub Actions pour publier le rapport allure
        publish_dir: ./allure-report
        #we dead it
    - name: Notify Slack # Envoie une notification Slack avec le lien vers le rapport Allure. (détails configuration à voir sur le fichier README)
      run: |
              curl -X POST -H 'Content-type: application/json' --data '{"text":"📊 *Le rapport Allure est maintenant disponible !* 🚀\n\nVous pouvez consulter le rapport complet en suivant ce lien : <https://awatagiltoo1.github.io/myshopifyTest/|Allure Report>"}' ${{ secrets.WEBHOOK_MYSHOPIFY }}